### PR TITLE
fix: byteswap fix under apple

### PR DESCRIPTION
**Pull request by kopinions**
fix compile under apple

### CODE REVIEW

**Comment by franciscoIglesias** [comment]
Hi Sun,

Thanks a lot for the patch!

May I ask you to please update the git commit message to below (for following the format of the other commits) and also add your Signed-off-by line?

```
remote-port-proto: Fix byteswaps under Apple

Signed-off-by: Sun JianKang <your email>
```

Best regards,
Francisco Iglesias

**Comment by kopinions** [comment]
Hi @franciscoIglesias commit message already changed.

**Comment by franciscoIglesias** [comment]
Hi,

May I ask you to change to you'r real name as author off the patch and also in the signed-off-by line? You can read more about this for example in: https://github.com/torvalds/linux/blob/master/Documentation/process/submitting-patches.rst

Thank you!
Best regards,
Francisco Iglesias

**Comment by kopinions** [comment]
Hi @franciscoIglesias,
author and the signed-off-by line all updated.

**Comment by franciscoIglesias** [comment]
Hi Sun,

Thank you for the patch! I just merged it: f59689ac187d8b38db9a682c43893c227988f18e.

Best regards,
Francisco Iglesias

**Pull request closed without merging**
